/**
 * Invoice Download API
 * Generates and downloads professional PDF invoice for The Yard Restaurant
 */

import { NextRequest, NextResponse } from 'next/server';
import { getAdminDb } from '@/lib/firebase-admin';
import { format } from 'date-fns';

interface InvoiceItem {
  name: string;
  quantity: number;
  price: number;
  subtotal: number;
}

interface Invoice {
  id: string;
  invoiceNumber: string;
  orderId: string;
  userId: string;
  customerName: string;
  customerEmail?: string;
  customerPhone?: string;
  items: InvoiceItem[];
  subtotal: number;
  serviceCharge: number;
  tax: number;
  total: number;
  paymentMethod: string;
  paymentStatus: string;
  paidAt?: Date;
  createdAt: Date;
  restaurant?: {
    name: string;
    address: string;
    phone: string;
    email: string;
  };
}

/**
 * Generate professional invoice text (PDF would use a library like jspdf or pdfkit)
 */
function generateInvoiceText(invoice: Invoice): string {
  const divider = '='.repeat(50);
  const line = '-'.repeat(50);
  
  const text = `
${divider}
                    THE YARD RESTAURANT
                      🌿 Fine Dining 🌿
${divider}

                    INVOICE

Invoice Number: ${invoice.invoiceNumber}
Date: ${invoice.createdAt instanceof Date ? format(invoice.createdAt, 'MMMM dd, yyyy') : format(new Date(invoice.createdAt), 'MMMM dd, yyyy')}
${invoice.paidAt ? `Paid: ${invoice.paidAt instanceof Date ? format(invoice.paidAt, 'MMMM dd, yyyy HH:mm') : format(new Date(invoice.paidAt), 'MMMM dd, yyyy HH:mm')}` : ''}

${line}
RESTAURANT DETAILS:
${line}
The Yard Restaurant
737 Rue Batibois
Douala, Cameroon
Phone: +237 671 490 733
Email: info@theyardrestaurant.com

${line}
BILL TO:
${line}
Customer: ${invoice.customerName}
${invoice.customerEmail ? `Email: ${invoice.customerEmail}` : ''}
${invoice.customerPhone ? `Phone: ${invoice.customerPhone}` : ''}

${line}
ORDER DETAILS:
${line}
${invoice.items.map(item => 
  `${item.name}
   ${item.quantity} x ${item.price.toLocaleString()} XAF = ${item.subtotal.toLocaleString()} XAF`
).join('\n')}

${line}
PAYMENT SUMMARY:
${line}
Subtotal:                           ${invoice.subtotal.toLocaleString()} XAF
Service Charge (5%):                ${invoice.serviceCharge.toLocaleString()} XAF
VAT (19.25%):                       ${invoice.tax.toLocaleString()} XAF
${line}
GRAND TOTAL:                        ${invoice.total.toLocaleString()} XAF
${divider}

Payment Method: ${invoice.paymentMethod}
Payment Status: ${invoice.paymentStatus}

${divider}
        Thank you for dining with us!
         We hope to see you again.

      Follow us: @theyardrestaurant
${divider}

Order Reference: #${invoice.orderId?.slice(-6).toUpperCase() || 'N/A'}

IMPORTANT NOTICE:
- This is a computer-generated invoice.
- Payment is non-refundable after 24 hours.
- For queries, contact: +237 671 490 733

Generated by The Yard Restaurant POS System
`.trim();

  return text;
}

/**
 * Generate HTML invoice for better formatting
 */
function generateInvoiceHTML(invoice: Invoice): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Invoice ${invoice.invoiceNumber}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
      background: #1c1917; 
      color: #ffffff; 
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header { 
      text-align: center; 
      border-bottom: 3px solid #d97706; 
      padding-bottom: 20px; 
      margin-bottom: 30px;
    }
    .logo { font-size: 32px; margin-bottom: 10px; }
    .brand { color: #d97706; font-size: 28px; font-weight: bold; }
    .tagline { color: #a8a29e; font-size: 14px; margin-top: 5px; }
    .invoice-title {
      font-size: 24px;
      color: #d97706;
      text-align: center;
      margin: 20px 0;
    }
    .details-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      margin-bottom: 30px;
    }
    .detail-box {
      background: #292524;
      border-radius: 8px;
      padding: 15px;
    }
    .detail-box h3 {
      color: #d97706;
      font-size: 14px;
      margin-bottom: 10px;
      text-transform: uppercase;
    }
    .detail-box p {
      color: #a8a29e;
      font-size: 14px;
      margin: 5px 0;
    }
    .detail-box .highlight {
      color: #ffffff;
      font-weight: 500;
    }
    .items-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }
    .items-table th {
      background: #292524;
      color: #d97706;
      padding: 12px;
      text-align: left;
      font-size: 12px;
      text-transform: uppercase;
    }
    .items-table td {
      padding: 12px;
      border-bottom: 1px solid #44403c;
      color: #d6d3d1;
    }
    .items-table .amount {
      text-align: right;
    }
    .summary-box {
      background: #292524;
      border-radius: 8px;
      padding: 20px;
      margin-top: 20px;
    }
    .summary-row {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #44403c;
    }
    .summary-row:last-child {
      border-bottom: none;
    }
    .summary-row.total {
      font-size: 20px;
      font-weight: bold;
      color: #d97706;
      border-top: 2px solid #d97706;
      margin-top: 10px;
      padding-top: 15px;
    }
    .payment-info {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      margin-top: 30px;
      padding: 15px;
      background: #292524;
      border-radius: 8px;
    }
    .status-paid { color: #22c55e; font-weight: bold; }
    .status-pending { color: #eab308; font-weight: bold; }
    .footer {
      text-align: center;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #44403c;
    }
    .footer p {
      color: #78716c;
      font-size: 12px;
      margin: 5px 0;
    }
    .footer .brand {
      color: #d97706;
      font-size: 16px;
      margin-bottom: 10px;
    }
    @media print {
      body { background: white; color: black; }
      .detail-box, .summary-box, .payment-info { background: #f5f5f5; }
      .items-table th { background: #e5e5e5; color: #333; }
      .items-table td { border-color: #ddd; color: #333; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">🌿</div>
    <div class="brand">THE YARD RESTAURANT</div>
    <div class="tagline">Restaurant • Bar • Terrace</div>
  </div>
  
  <h1 class="invoice-title">INVOICE</h1>
  
  <div class="details-grid">
    <div class="detail-box">
      <h3>Invoice Details</h3>
      <p>Invoice #: <span class="highlight">${invoice.invoiceNumber}</span></p>
      <p>Date: <span class="highlight">${invoice.createdAt instanceof Date ? format(invoice.createdAt, 'MMMM dd, yyyy') : format(new Date(invoice.createdAt), 'MMMM dd, yyyy')}</span></p>
      ${invoice.paidAt ? `<p>Paid: <span class="highlight">${invoice.paidAt instanceof Date ? format(invoice.paidAt, 'MMMM dd, yyyy HH:mm') : format(new Date(invoice.paidAt), 'MMMM dd, yyyy HH:mm')}</span></p>` : ''}
    </div>
    
    <div class="detail-box">
      <h3>Bill To</h3>
      <p class="highlight">${invoice.customerName}</p>
      ${invoice.customerEmail ? `<p>${invoice.customerEmail}</p>` : ''}
      ${invoice.customerPhone ? `<p>${invoice.customerPhone}</p>` : ''}
    </div>
  </div>
  
  <div class="detail-box" style="margin-bottom: 20px;">
    <h3>Restaurant Details</h3>
    <p class="highlight">The Yard Restaurant</p>
    <p>737 Rue Batibois, Douala, Cameroon</p>
    <p>Phone: +237 671 490 733</p>
    <p>Email: info@theyardrestaurant.com</p>
  </div>
  
  <table class="items-table">
    <thead>
      <tr>
        <th>Item</th>
        <th style="text-align: center;">Qty</th>
        <th style="text-align: right;">Price</th>
        <th style="text-align: right;">Subtotal</th>
      </tr>
    </thead>
    <tbody>
      ${invoice.items.map(item => `
        <tr>
          <td>${item.name}</td>
          <td style="text-align: center;">${item.quantity}</td>
          <td class="amount">${item.price.toLocaleString()} XAF</td>
          <td class="amount">${item.subtotal.toLocaleString()} XAF</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  
  <div class="summary-box">
    <div class="summary-row">
      <span>Subtotal</span>
      <span>${invoice.subtotal.toLocaleString()} XAF</span>
    </div>
    <div class="summary-row">
      <span>Service Charge (5%)</span>
      <span>${invoice.serviceCharge.toLocaleString()} XAF</span>
    </div>
    <div class="summary-row">
      <span>VAT (19.25%)</span>
      <span>${invoice.tax.toLocaleString()} XAF</span>
    </div>
    <div class="summary-row total">
      <span>GRAND TOTAL</span>
      <span>${invoice.total.toLocaleString()} XAF</span>
    </div>
  </div>
  
  <div class="payment-info">
    <div>
      <p style="color: #d97706; font-weight: 500;">Payment Method</p>
      <p style="font-size: 16px; margin-top: 5px;">${invoice.paymentMethod}</p>
    </div>
    <div style="text-align: right;">
      <p style="color: #d97706; font-weight: 500;">Payment Status</p>
      <p class="${invoice.paymentStatus === 'PAID' ? 'status-paid' : 'status-pending'}" style="font-size: 16px; margin-top: 5px;">
        ${invoice.paymentStatus}
      </p>
    </div>
  </div>
  
  <div class="footer">
    <p class="brand">🌿 THE YARD RESTAURANT</p>
    <p>Thank you for dining with us! We hope to see you again.</p>
    <p>Follow us: @theyardrestaurant</p>
    <br>
    <p>This is a computer-generated invoice.</p>
    <p>For queries, contact: +237 671 490 733</p>
  </div>
</body>
</html>
`;
}

/**
 * GET /api/invoices/[id]/download
 * Download invoice as HTML or text file
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const adminDb = getAdminDb();
    
    if (!adminDb) {
      return NextResponse.json(
        { error: 'Database unavailable' },
        { status: 503 }
      );
    }
    
    // Get invoice
    const invoiceDoc = await adminDb.collection('invoices').doc(id).get();
    
    if (!invoiceDoc.exists) {
      // Try to find by orderId
      const invoiceQuery = await adminDb.collection('invoices')
        .where('orderId', '==', id)
        .limit(1)
        .get();
      
      if (invoiceQuery.empty) {
        return NextResponse.json(
          { error: 'Invoice not found' },
          { status: 404 }
        );
      }
      
      const foundDoc = invoiceQuery.docs[0];
      const invoice = foundDoc.data() as Invoice;
      invoice.id = foundDoc.id;
      
      const { searchParams } = new URL(request.url);
      const format = searchParams.get('format') || 'html';
      
      if (format === 'text') {
        const text = generateInvoiceText(invoice);
        return new NextResponse(text, {
          headers: {
            'Content-Type': 'text/plain',
            'Content-Disposition': `attachment; filename="invoice-${invoice.invoiceNumber}.txt"`,
          },
        });
      }
      
      const html = generateInvoiceHTML(invoice);
      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="invoice-${invoice.invoiceNumber}.html"`,
        },
      });
    }
    
    const invoice = { id: invoiceDoc.id, ...invoiceDoc.data() } as Invoice;
    
    const { searchParams } = new URL(request.url);
    const format = searchParams.get('format') || 'html';
    
    if (format === 'text') {
      const text = generateInvoiceText(invoice);
      return new NextResponse(text, {
        headers: {
          'Content-Type': 'text/plain',
          'Content-Disposition': `attachment; filename="invoice-${invoice.invoiceNumber}.txt"`,
        },
      });
    }
    
    const html = generateInvoiceHTML(invoice);
    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="invoice-${invoice.invoiceNumber}.html"`,
      },
    });
    
  } catch (error) {
    console.error('Error downloading invoice:', error);
    return NextResponse.json(
      { error: 'Failed to download invoice' },
      { status: 500 }
    );
  }
}
